---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: db-secret
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgARZN6GTJECUyAyWq1X4QASZvsXoD5EydUtLhWEn9Ivdt1h+nkOeJN595ie5B5dWy6UDk1G18vsH/htU69JbPaFVV/Qtsh7iL8izOOyezuEWRysSIYnZb0I1HzjakHoCbyizcBP4330M4yyjZa67L4pFXnOqLqHiMSXMfexuVlUsBbxDZYTiSmAS+0Imdw5FlFWcocJEDSfntx4oumIm/L6xmWYY500WNhERnJyqxmkY/fqSlPQA49HsJpsWTkcRIl0zPTFJthjIlaIWgNHMH4nei9Qni3cR5wMKXg4QF2QsM+JRKzvrzKztvhJ7aO57DUk53O+YgPE39zXoBhTmPv9k4nMOiwA6B3T7gp7UvRHpxQpWAhfjGMj6+8VtND4QgjSX9ddE1+h7XKDpPiVwjvw92TuvAl/dJ7GyjJd075Rsb9s6daFW5v3en3Ck093oMNjs7Q3FKTTZYkzuoxGzRDb2wU3uMjqpu0CXVuAlhs0YO1c2LWCSVfxs0ZtAakBcC03bbw5MwCWFHOklL3cw695cW+HbpsikAchFVOawVuHKTiw8c7DaYCuCrEYAMoYf995nRxTHT0i3sdD9u4ayd6NwBaBtd1hSbjbS0cEfgBKELy6m2lkKOKYKQua6LJ+IMplSAPgpzssBaTNB9B0WL4IFsTqBRFmyKuW49aJBEqLPoh8UgWiRMqVCxB5/5NR01Ev82x3fyxFxQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: db-secret
