---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgAkAw9yHQZ02oAWwClwxbO0uSC0NN96LZyNy9PhE8TRT2L0ESSRsgNA/zrkKtb0RTIHz2q7zNFYjSAXuB8CNmPYhvNrK6MijOFyHeZfePQz3YTyQFdN8QjB7WvHPYRlas3r6f30o+7FEo6XIwHw/tuRIHvswsc30T9PMDLqCyI6IwqhYpOAtRK8hoKCpo9LEz1IVpFFcrNCXbR9VM5akgnPOebbUND70hhn7zUNZxpXvSwlnH37qKMcCmtkFuVBJHWUWLbdEZDEeM3vjS9rJKlrDHAUkkfs5Tane/V1Tx8bhfvXXnha4bQEwa3vfp6pYhxb/xlUKI0CJeZV3/roIh1h0xjM8xVBKU/Pjp11DDUWjlgTUQvphJapkiJlFcbOZAQWy25XeRdxe8Mam2EORG93MNtZ23HvRTIBtxWJvlC8JUazQ4e/ZG8iv2aamJg0JwTpOJrJ4sLvb2BhQZL+tbDBqaKAdhu68jbczruicCDeqr/lbwPuJIwSC1I3uWU54Vt4TnhYgyOgtQUFmPdjgxQpQWWxZRjOh7RlAfG03g/X2U7RmhvKtthXcdGtdYJGVgrlmx1JZR8JcCAYZ1SHTSLOWNReuXKMjvE1RCfuIG3QiQHS/nUiIPU//ln3SByeFLIH6Ra1GnaIsHgj1THP/Hi4CXucNZj83q60IeVKVdjZrOnEpvpYHdjibvFhWHQ4ubne8TOauT0Yew==
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
