apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - dev-ns.yaml

namespace: dev

labels:
  - pairs:
      environement: dev

patches:
  - path: db-depl-patch.yaml

nameSuffix: -dev
