apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: mysql
        env:  
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret-uat
              key: MYSQL_ROOT_PASSWORD

