apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - uat-ns.yaml

namespace: uat

labels:
  - pairs:
      environment: uat

patches:
  - path: web-depl-patch.yaml
  - path: db-depl-patch.yaml

nameSuffix: -uat